CREATE TABLE IF NOT EXISTS SOURCES (
url TEXT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS IMAGES (
url TEXT PRIMARY KEY,
source TEXT NOT NULL,
title TEXT NOT NULL,
rate INTEGER NOT NULL,
size INTEGER,
color TEXT,
adddate DATE,
date DATE,
place DATE,
format TEXT,
FOREIGN KEY(source) REFERENCES SOURCES(url)
);

CREATE TABLE IF NOT EXISTS IMAGES_NOTES (
note TEXT NOT NULL,
url TEXT NOT NULL,
PRIMARY KEY (note, url),
FOREIGN KEY(url) REFERENCES IMAGES(url)
);
